info:
  contact: {}
paths:
  /books:
    get:
      consumes:
      - application/json
      description: get books
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: get books
      tags:
      - books
  /users:
    get:
      consumes:
      - application/json
      description: get users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: get users
      tags:
      - books
swagger: "2.0"
